# https://taskfile.dev

version: '3'

vars:
  LOG_DIR: .data/logs
  AWS_SCRIPTS_PATH: /workspace/.claude/aws
  DOCKERFILE_PATH: '{{.DOCKERFILE_PATH | default "/workspace/.claude/docker/Dockerfile"}}'
  ACCOUNT: '{{.ACCOUNT | default "root"}}'
  PARENT_PATH:
    sh: |
      pwsh -NoProfile -Command "
        \$parent = (Resolve-Path '{{.ROOT_DIR}}/..').Path
        Write-Output \$parent.ToLower()
      "
  SLUG:
    sh: |
      pwsh -NoProfile -Command "
        \$slug = '{{.PARENT_PATH}}' -replace '^([A-Za-z]):', '/\$1' -replace '\\\\', '/'
        Write-Output \$slug.ToLower()
      "

env:
  PARENT_PATH: "{{.PARENT_PATH}}"
  SLUG: "{{.SLUG}}"

tasks:
  default:
    cmds:
      - cmd: task --list-all
    silent: true

  ensure-env:
    desc: Ensures a .env is present, even if empty
    cmds:
      - cmd: touch ./.env
        platforms: [linux, darwin]
      - cmd: pwsh -Command "if (!(Test-Path ./.env)) { New-Item -Path ./.env -ItemType File -Force | Out-Null }"
        platforms: [windows]
    silent: true

  host:claude:build:
    desc: Builds the claude image
    aliases:
      - build
    deps:
      - ensure-env
    cmds:
      - docker compose build
    silent: true

  claude:
    desc: Runs claude in a container
    deps:
      - ensure-env
    cmds:
      - >-
        pwsh -c "
        if (Test-Path /.dockerenv) {
          Set-Location "/workspace/${env:CLAUDE_PROJECT_SLUG}"
          claude update
          claude --continue 2>\$null || claude
        } else {
          docker compose build
          docker compose run --remove-orphans claude run-claude
        }"
    silent: true

  host:claude:shell:
    desc: Runs the claude container in shell mode
    aliases:
      - shell
    deps:
      - ensure-env
      - build
    cmds:
      - docker compose run --remove-orphans claude shell
    silent: true

  host:claude:config:
    desc: docker-compose config
    aliases:
      - config
    deps:
      - ensure-env
    cmds:
      - docker compose config claude
    silent: true

  host:ensure-host:
    desc: Determines if running in on the host
    aliases:
      - ensure-host
    preconditions:
      - sh: test ! -f /.dockerenv
        msg: "This task can only be run on the host"
    cmds:
      - echo "Running on the host"
    silent: true

  host:delete-logs-folder:
    aliases:
      - delete-logs
    deps:
      - ensure-host
    vars:
      TARGET_PATH: '.data/logs'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted logs..."
    silent: true

  host:delete-data-folder:
    aliases:
      - delete-data
    deps:
      - ensure-host
    vars:
      TARGET_PATH: '.data/'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    prompt: This will delete the {{.TARGET_PATH}} folder. Continue?
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted data folder..."
    silent: true

  host:clean-docker:
    desc: Kills and removes all running containers on the host
    aliases:
      - clean
    deps:
      - ensure-env
    cmds:
      - docker kill $(docker ps -q) 2>/dev/null || true
      - docker rm -f $(docker ps -aq) 2>/dev/null || true
      - docker image prune -f
      - task: delete-logs
    silent: true

  host:purge-docker:
    aliases:
      - purge
    deps:
      - ensure-env
      - clean
    cmds:
      - cmd: docker volume rm $(docker volume ls -q) 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - task: delete-data
    silent: true

  host:nuke-docker:
    desc: Nukes docker. Beware.
    aliases:
      - nuke
    deps:
      - ensure-env
      - purge
    cmds:
      - cmd: docker system prune -f -a --volumes 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - cmd: docker network rm $(docker network ls -q) 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - cmd: docker rmi -f $(docker images -aq) 2>/dev/null || true
        platforms: [linux, darwin, windows]
    silent: true

  host:git:fetch:
    desc: Update .claude submodule from origin
    aliases:
      - pull
      - fetch
      - get
    deps:
      - ensure-host
    cmds:
      - git -C .claude fetch origin && git -C .claude reset --hard origin/main
    silent: true

  host:git:trivial-update:
    desc: creates a commit with a '{{.MSG}}' message and pushes it
    aliases:
      - trivial
    vars:
      MSG: '{{.MSG | default "(chore) trivial update"}}'
    preconditions:
      - sh: '[ -n "$(git status --porcelain)" ]'
        msg: "No changes to commit"
    cmds:
      - git status
      - git add --all
      - git commit -m '{{.MSG}}'
      - git push
      - git status
    silent: true

  claude:ensure-docker:
    desc: Determines if running in a container
    aliases:
      - ensure-docker
    preconditions:
      - sh: test -f /.dockerenv
        msg: "This task can only be run inside a Docker container"
    cmds:
      - echo "/.dockerenv exists"
    silent: true

  aws:sso:login:
    desc: "Login to AWS SSO (interactive menu if ACCOUNT not specified)"
    aliases:
      - login
    deps:
      - ensure-docker
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:ensure ACCOUNT=<alias>"
    vars:
      _ACCOUNT: '{{.ACCOUNT | default "manager"}}'
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/sso_login.py {{.ACCOUNT}} {{if .FORCE}}--force{{end}}
    silent: true

  aws:sso:check:
    desc: "Check SSO credential status (usage: task sso:check ACCOUNT=sandbox)"
    aliases:
      - check
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/sso_check.py {{.ACCOUNT}}
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:check ACCOUNT=<alias>"
    silent: true

  aws:sso:ensure-login:
    desc: "Ensure SSO credentials valid - silent mode for automation"
    aliases:
      - ensure-aws-login
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/sso_ensure.py {{.ACCOUNT}}
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:ensure ACCOUNT=<alias>"
    silent: true

  aws:sso:list-accounts:
    desc: "List all configured accounts"
    aliases:
      - list-accounts
    cmds:
      - |
        echo "Configured accounts:"
        grep -E "^  [a-z]" aws.yml | grep -v "account_" | sed 's/://g' | sed 's/^  /  - /'
    silent: true

  aws:sso:update:
    desc: "Sync aws.yml with AWS Organizations hierarchy"
    aliases:
      - org:sync
      - update-accounts
    deps:
      - ensure-docker
    cmds:
      - |
        uv run {{.AWS_SCRIPTS_PATH}}/sso_ensure.py root || {
          echo "Root account credentials required. Run: task login ACCOUNT=root"
          exit 1
        }
      - uv run {{.AWS_SCRIPTS_PATH}}/org_sync.py {{if .DRY_RUN}}--dry-run{{end}}
    silent: true
