# https://taskfile.dev

version: '3'

includes:
  internal:
    taskfile: "tasks/internal-tasks/Taskfile.yml"
    internal: true
    flatten: true
  docker:
    taskfile: "tasks/docker-tasks"
    internal: false
    flatten: true
  git:
    taskfile: "tasks/git-tasks"
    internal: false
    flatten: true
  playwright:
    taskfile: "tasks/playwright-tasks"
    internal: false
    flatten: true
  rules:
    taskfile: "tasks/rules-tasks"
    internal: false
    flatten: true

vars:
  # // HOST PATHS \\
  TASKFILE_PARENT:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "Split-Path -Parent '{{.TASKFILE_DIR}}'"
      {{else}}
        dirname "{{.TASKFILE_DIR}}"
      {{end}}
  HOST_HOME_PATH:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "
          Write-Output \$env:USERPROFILE
        "
      {{else}}
        echo "$HOME"
      {{end}}
  HOST_CLAUDE_ROOT_PATH:
    sh: |
      {{if eq .OS "Windows_NT"}}
        echo '{{.HOST_HOME_PATH}}\.claude\_docker\{{.CLAUDE_PROJECT_SLUG}}'
      {{else}}
        echo '{{.HOST_HOME_PATH}}/.claude/_docker/{{.CLAUDE_PROJECT_SLUG}}'
      {{end}}

  # // HOST LINUX STYLE PATHS \\
  DOCKER_SOCK_PATH:
    sh: |
      OS_TYPE=$(docker version --format '{{.Server.Os}}' 2>/dev/null)
      case "$OS_TYPE" in
        windows|Windows|Windows_NT|WINDOWS)
          echo "//./pipe/docker_engine"
          ;;
        *)
          if [ -S "/var/run/docker.sock" ]; then
            echo "/var/run/docker.sock"
          elif [ -S "$HOME/.docker/run/docker.sock" ]; then
            echo "$HOME/.docker/run/docker.sock"
          else
            echo "/var/run/docker.sock"
          fi
          ;;
      esac
  HOME_DIR:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "
          \$winhome = \$env:USERPROFILE -replace '^([A-Za-z]):', '/\$1' -replace '\\\\', '/'
          Write-Output \$winhome.ToLower()
        "
      {{else}}
        echo "$HOME"
      {{end}}
  CLAUDE_DIR:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "
          \$dir = '{{.TASKFILE_DIR}}' -replace '^([A-Za-z]):', '/\$1' -replace '\\\\', '/'
          Write-Output \$dir.ToLower()
        "
      {{else}}
        echo "{{.TASKFILE_DIR}}" | tr '[:upper:]' '[:lower:]'
      {{end}}
  CLAUDE_PARENT_DIR:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "
          \$dir = '{{.TASKFILE_PARENT}}' -replace '^([A-Za-z]):', '/\$1' -replace '\\\\', '/'
          Write-Output \$dir.ToLower()
        "
      {{else}}
        dirname "{{.CLAUDE_DIR}}"
      {{end}}
  CLAUDE_PROJECT_SLUG:
    sh: |
      {{if eq .OS "Windows_NT"}}
        pwsh -NoProfile -Command "
          \$slug = '{{.CLAUDE_PARENT_DIR}}'.TrimStart('/') -replace '/', '-'
          Write-Output \$slug.ToLower()
        "
      {{else}}
        echo "{{.CLAUDE_PARENT_DIR}}" | sed 's|^/||' | tr '/' '-' | tr '[:upper:]' '[:lower:]'
      {{end}}
  CLAUDE_DOCKERFILE_PATH: "{{.CLAUDE_DIR}}/docker/Dockerfile"
  CLAUDE_DATA_PATH: "{{.CLAUDE_DIR}}/.data"
  CLAUDE_LOG_PATH: "{{.CLAUDE_DIR}}/.data/logs"
  CLAUDE_ROOT_PATH: "{{.HOME_DIR}}/.claude/_docker/{{.CLAUDE_PROJECT_SLUG}}"
  CLAUDE_CONFIG_YML_PATH: "{{.CLAUDE_DIR}}/config.yml"
  HOME_SSH_PATH: "{{.HOME_DIR}}/.ssh"

env:
  # // TASKFILE NATIVE VARS \\
  OS: "{{.OS}}"
  TASK_VERSION: "{{.TASK_VERSION}}"
  TASK: "{{.TASK}}"
  TASKFILE: "{{.TASKFILE}}"
  TASKFILE_DIR: "{{.TASKFILE_DIR}}"
  ROOT_DIR: "{{.ROOT_DIR}}"
  USER_WORKING_DIR: "{{.USER_WORKING_DIR}}"

  # // HOST PATHS \\
  TASKFILE_PARENT: "{{.TASKFILE_PARENT}}"
  HOST_HOME_PATH: "{{.HOST_HOME_PATH}}"
  HOST_CLAUDE_ROOT_PATH: "{{.HOST_CLAUDE_ROOT_PATH}}"

  # // HOST LINUX STYLE PATHS \\
  HOME_DIR: "{{.HOME_DIR}}"
  HOME_SSH_PATH: "{{.HOME_SSH_PATH}}"
  CLAUDE_DIR: "{{.CLAUDE_DIR}}"
  CLAUDE_DATA_PATH: "{{.CLAUDE_DATA_PATH}}"
  CLAUDE_LOG_PATH: "{{.CLAUDE_LOG_PATH}}"
  CLAUDE_PARENT_DIR: "{{.CLAUDE_PARENT_DIR}}"
  CLAUDE_PROJECT_SLUG: "{{.CLAUDE_PROJECT_SLUG}}"
  CLAUDE_ROOT_PATH: "{{.CLAUDE_ROOT_PATH}}"
  CLAUDE_CONFIG_YML_PATH: "{{.CLAUDE_CONFIG_YML_PATH}}"
  CLAUDE_DOCKERFILE_PATH: "{{.CLAUDE_DOCKERFILE_PATH}}"
  DOCKER_SOCK_PATH: "{{.DOCKER_SOCK_PATH}}"

tasks:
  claude:default:
    aliases:
      - default
    cmds:
      - cmd: task --list-all

  claude:clear:
    aliases:
      - clear
    cmds:
      - cmd: clear
        platforms: [linux, darwin]
      - cmd: 'pwsh -NoProfile -Command "[Console]::Clear()"'
        platforms: [windows]
    silent: true

  ensure-env:
    desc: Ensures a .env is present, even if empty
    aliases:
      - ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: >-
          pwsh -c "
          if (!(Test-Path '.env')) {
            cp '.env.example' '.env'
          }"
    silent: true

  claude:ensure-host:
    desc: Determines if running in on the host
    aliases:
      - ensure-host
    preconditions:
      - sh: test ! -f /.dockerenv
        msg: "This task can only be run on the host"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - echo "Running on the host"
    silent: true

  claude:env:
    aliases:
      - env
    deps:
      - ensure-host
    cmds:
      - task: clear
      - cmd: "echo"
      - task: info
        vars: { MSG: "----- TASKFILE NATIVE VARS -----" }
      - task: print-var
        vars: { K: "OS", V: "{{.OS}}" }
      - task: print-var
        vars: { K: "TASK_VERSION", V: "{{.TASK_VERSION}}" }
      - task: print-var
        vars: { K: "TASK", V: "{{.TASK}}" }
      - task: print-var
        vars: { K: "TASKFILE", V: "{{.TASKFILE}}" }
      - task: print-var
        vars: { K: "TASKFILE_DIR", V: "{{.TASKFILE_DIR}}" }
      - task: print-var
        vars: { K: "ROOT_DIR", V: "{{.ROOT_DIR}}" }
      - task: print-var
        vars: { K: "USER_WORKING_DIR", V: "{{.USER_WORKING_DIR}}" }

      - cmd: "echo"
      - task: info
        vars: { MSG: "----- HOST PATHS -----" }
      - task: print-var
        vars: { K: "TASKFILE_PARENT", V: "{{.TASKFILE_PARENT}}" }
      - task: print-var
        vars: { K: "HOST_HOME_PATH", V: "{{.HOST_HOME_PATH}}" }
      - task: print-var
        vars: { K: "HOST_CLAUDE_ROOT_PATH", V: "{{.HOST_CLAUDE_ROOT_PATH}}" }

      - cmd: "echo"
      - task: info
        vars: { MSG: "----- HOST LINUX STYLE PATHS-----" }
      - task: print-var
        vars: { K: "HOME_DIR", V: "{{.HOME_DIR}}" }
      - task: print-var
        vars: { K: "HOME_SSH_PATH", V: "{{.HOME_SSH_PATH}}" }
      - task: print-var
        vars: { K: "DOCKER_SOCK_PATH", V: "{{.DOCKER_SOCK_PATH}}" }
      - task: print-var
        vars: { K: "CLAUDE_DIR", V: "{{.CLAUDE_DIR}}" }
      - task: print-var
        vars: { K: "CLAUDE_PARENT_DIR", V: "{{.CLAUDE_PARENT_DIR}}" }
      - task: print-var
        vars: { K: "CLAUDE_DATA_PATH", V: "{{.CLAUDE_DATA_PATH}}" }
      - task: print-var
        vars: { K: "CLAUDE_LOG_PATH", V: "{{.CLAUDE_LOG_PATH}}" }
      - task: print-var
        vars: { K: "CLAUDE_PROJECT_SLUG", V: "{{.CLAUDE_PROJECT_SLUG}}" }
      - task: print-var
        vars: { K: "CLAUDE_CONFIG_YML_PATH", V: "{{.CLAUDE_CONFIG_YML_PATH}}" }
      - task: print-var
        vars: { K: "CLAUDE_DOCKERFILE_PATH", V: "{{.CLAUDE_DOCKERFILE_PATH}}" }
      - task: print-var
        vars: { K: "CLAUDE_ROOT_PATH", V: "{{.CLAUDE_ROOT_PATH}}" }

      - cmd: "echo"
      - task: wait
        vars: { SECONDS: 2 }
    silent: true

  claude:build:
    desc: Builds the claude image
    aliases:
      - build
    deps:
      - ensure-host
      - ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose build
    silent: true

  claude:push:
    desc: Pushes the image to dockerhub
    aliases:
      - push
    deps:
      - ensure-host
      - ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose push
    silent: true

  claude:claude:
    desc: Runs claude in a container
    aliases:
      - claude
      - ai
      - start
      - vibe
    deps:
      - ensure-host
      - ensure-env
      - ensure-stack-network
      - build
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose run --remove-orphans claude run-claude '{{.CLI_ARGS}}'
    interactive: true
    silent: true

  claude:stream:
    desc: A no persistence query to claude
    aliases:
      - stream
    deps:
      - ensure-stack-network
      - build
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose run --remove-orphans claude run-claude '-stream_claude {{.CLI_ARGS}}'
    silent: true

  claude:debug:
    desc: Runs claude in a container in debug mode
    aliases:
      - debug
    deps:
      - ensure-stack-network
      - build
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose run --remove-orphans claude run-claude '-debug_claude'
    silent: true

  claude:shell:
    desc: Runs the claude container in shell mode
    aliases:
      - shell
    deps:
      - ensure-stack-network
      - build
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose run --remove-orphans claude shell
    silent: true

  claude:test:
    desc: Runs the claude container in test mode
    aliases:
      - test
      - doctor
    deps:
      - ensure-stack-network
      - pull
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - task: clear
      - docker compose run --remove-orphans claude run-test '{{.CLI_ARGS}}'
    silent: true

  claude:config:
    desc: docker-compose config
    aliases:
      - config
    deps:
      - ensure-host
      - ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose config claude
    silent: true

  claude:delete-logs-folder:
    aliases:
      - delete-logs-folder
    deps:
      - ensure-host
    vars:
      TARGET_PATH: '.data/logs'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted logs..."
    silent: true

  claude:delete-data-folder:
    aliases:
      - delete-data-folder
    deps:
      - ensure-host
    vars:
      TARGET_PATH: '.data/'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    prompt: This will delete the {{.TARGET_PATH}} folder. Continue?
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted data folder..."
    silent: true

  claude:delete-home-claude-config:
    aliases:
      - delete-home-claude-config
    deps:
      - ensure-host
    vars:
      TARGET_PATH: "{{.HOST_CLAUDE_ROOT_PATH}}"
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    prompt: This will delete the {{.TARGET_PATH}} folder. Continue?
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted {{.TARGET_PATH}} folder..."
    silent: true

  # // LIB TASKS \\

  lib:test:
    desc: Run lib/ tests
    aliases:
      - lib-test
    dir: "{{.CLAUDE_DIR}}/lib"
    cmds:
      - uv run pytest tests/ -v
    silent: false

  lib:test-cov:
    desc: Run lib/ tests with coverage
    aliases:
      - lib-test-cov
    dir: "{{.CLAUDE_DIR}}/lib"
    cmds:
      - uv run pytest tests/ -v --cov=aws_utils --cov=config_helper --cov-report=term-missing
    silent: false

  lib:lint:
    desc: Lint lib/ code
    aliases:
      - lib-lint
    dir: "{{.CLAUDE_DIR}}/lib"
    cmds:
      - uv run ruff check .
    silent: false

  lib:lint-fix:
    desc: Lint and fix lib/ code
    aliases:
      - lib-lint-fix
    dir: "{{.CLAUDE_DIR}}/lib"
    cmds:
      - uv run ruff check --fix .
    silent: false

  lib:sync:
    desc: Sync lib/ dependencies
    aliases:
      - lib-sync
    dir: "{{.CLAUDE_DIR}}/lib"
    cmds:
      - uv sync
    silent: false
