# https://taskfile.dev

version: '3'

vars:
  LOG_DIR: "{{.TASKFILE_DIR}}/.data/logs"
  AWS_SCRIPTS_PATH: "{{.TASKFILE_DIR}}/.claude/aws"
  DOCKERFILE_PATH: '{{.DOCKERFILE_PATH | default "{{.TASKFILE_DIR}}/.claude/docker/Dockerfile"}}'
  AWS_ACCOUNT: '{{.AWS_ACCOUNT | default "root"}}'
  PARENT_PATH:
    sh: |
      pwsh -NoProfile -Command "
        \$parent = (Resolve-Path '{{.TASKFILE_DIR}}/..').Path
        Write-Output \$parent.ToLower()
      "
  SLUG:
    sh: |
      pwsh -NoProfile -Command "
        \$slug = '{{.PARENT_PATH}}' -replace '^([A-Za-z]):', '/\$1' -replace '\\\\', '/'
        Write-Output \$slug.ToLower()
      "

env:
  PARENT_PATH: "{{.PARENT_PATH}}"
  SLUG: "{{.SLUG}}"

tasks:
  claude:default:
    aliases:
      - default
    cmds:
      - cmd: "echo 'TASKFILE_DIR: {{.TASKFILE_DIR}}'"
      - cmd: "echo 'LOG_DIR: {{.LOG_DIR}}'"
      - cmd: "echo 'AWS_SCRIPTS_PATH: {{.AWS_SCRIPTS_PATH}}'"
      - cmd: "echo 'DOCKERFILE_PATH: {{.DOCKERFILE_PATH}}'"
      - cmd: "echo 'AWS_ACCOUNT: {{.AWS_ACCOUNT}}'"
      - cmd: "echo 'PARENT_PATH: {{.PARENT_PATH}}'"
      - cmd: "echo 'SLUG: {{.SLUG}}'"
      - cmd: "echo '---'"
      - cmd: task --list-all
    silent: true

  claude:ensure-env:
    desc: Ensures a .env is present, even if empty
    cmds:
      - cmd: touch ./.env
        platforms: [linux, darwin]
      - cmd: pwsh -Command "if (!(Test-Path ./.env)) { New-Item -Path ./.env -ItemType File -Force | Out-Null }"
        platforms: [windows]
    silent: true

  claude:claude:
    desc: Runs claude in a container
    aliases:
      - claude
    deps:
      - claude:ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - >-
        pwsh -c "
        if (Test-Path /.dockerenv) {
          Set-Location "{{.TASKFILE_DIR}}/${env:CLAUDE_PROJECT_SLUG}"
          claude update
          claude --continue 2>\$null || claude
        } else {
          docker compose build
          docker compose run --remove-orphans claude run-claude
        }"
    silent: true

  claude:build:
    desc: Builds the claude image
    aliases:
      - build
    deps:
      - claude:ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose build
    silent: true

  claude:shell:
    desc: Runs the claude container in shell mode
    aliases:
      - shell
    deps:
      - claude:ensure-env
      - claude:build
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose run --remove-orphans claude shell
    silent: true

  claude:trivial:
    aliases:
      - trivial
    desc: Create a trivial commit and push
    vars:
      MSG: '{{.MSG | default "(chore) trivial update"}}'
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - pwsh -NoProfile -File scripts/trivial-commit.ps1 -Message "{{.MSG}}"
    silent: true

  claude:fetch:
    aliases:
      - fetch
    desc: Fetch and reset .claude submodule to origin/main
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - pwsh -NoProfile -File .scripts/fetch-submodule.ps1
    silent: true

  claude:update:
    aliases:
      - update
    desc: Commit and sync .claude submodule changes
    vars:
      MSG: '{{.MSG | default "chore: update .claude"}}'
      BRANCH: '{{.BRANCH | default "main"}}'
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - pwsh -NoProfile -File .claude/scripts/update-submodule.ps1 -Message "{{.MSG}}" -Branch "{{.BRANCH}}"
    silent: true

  claude:config:
    desc: docker-compose config
    aliases:
      - config
    deps:
      - claude:ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker compose config claude
    silent: true

  claude:ensure-host:
    desc: Determines if running in on the host
    aliases:
      - ensure-host
    preconditions:
      - sh: test ! -f /.dockerenv
        msg: "This task can only be run on the host"
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - echo "Running on the host"
    silent: true

  claude:delete-logs-folder:
    aliases:
      - claude:delete-logs-folder
    deps:
      - claude:ensure-host
    vars:
      TARGET_PATH: '.data/logs'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted logs..."
    silent: true

  claude:delete-data-folder:
    aliases:
      - delete-data-folder
    deps:
      - claude:ensure-host
    vars:
      TARGET_PATH: '.data/'
    desc: Remove the {{.TARGET_PATH}} folder from the current directory
    prompt: This will delete the {{.TARGET_PATH}} folder. Continue?
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: rm -rf {{.TARGET_PATH}}
        platforms: [linux, darwin]
      - cmd: pwsh -Command "Remove-Item -Path '{{.TARGET_PATH}}' -Recurse -Force -ErrorAction SilentlyContinue; exit 0"
        platforms: [windows]
      - cmd: echo "deleted data folder..."
    silent: true

  claude:clean-docker:
    desc: Kills and removes all running containers on the host
    deps:
      - claude:ensure-env
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - docker kill $(docker ps -q) 2>/dev/null || true
      - docker rm -f $(docker ps -aq) 2>/dev/null || true
      - docker image prune -f
      - task: delete-logs
    silent: true

  claude:purge-docker:
    aliases:
      - purge
    deps:
      - claude:ensure-env
      - claude:clean
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: docker volume rm $(docker volume ls -q) 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - task: delete-data
    silent: true

  claude:nuke-docker:
    desc: Nukes docker. Beware.
    aliases:
      - nuke
    deps:
      - claude:ensure-env
      - claude:purge
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - cmd: docker system prune -f -a --volumes 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - cmd: docker network rm $(docker network ls -q) 2>/dev/null || true
        platforms: [linux, darwin, windows]
      - cmd: docker rmi -f $(docker images -aq) 2>/dev/null || true
        platforms: [linux, darwin, windows]
    silent: true

  claude:ensure-docker:
    desc: Determines if running in a container
    aliases:
      - ensure-docker
    preconditions:
      - sh: test -f /.dockerenv
        msg: "This task can only be run inside a Docker container"
    cmds:
      - echo "/.dockerenv exists"
    silent: true

  aws-login:
    desc: "Login to AWS SSO (interactive menu if ACCOUNT not specified)"
    aliases:
      - login
    deps:
      - claude:ensure-docker
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:ensure ACCOUNT=<alias>"
    vars:
      _ACCOUNT: '{{.ACCOUNT | default "manager"}}'
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/cli/sso_login.py {{.ACCOUNT}} {{if .FORCE}}--force{{end}}
    silent: true

  aws-check:
    desc: "Check SSO credential status (usage: task sso:check ACCOUNT=sandbox)"
    aliases:
      - check
    deps:
      - claude:ensure-docker
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/cli/sso_check.py {{.ACCOUNT}}
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:check ACCOUNT=<alias>"
    silent: true

  aws-ensure-login:
    aliases:
      - ensure-login
    desc: "Ensure SSO credentials valid - silent mode for automation"
    deps:
      - claude:ensure-docker
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run {{.AWS_SCRIPTS_PATH}}/cli/sso_check.py --quiet {{.ACCOUNT}}
    preconditions:
      - sh: '[ -n "{{.ACCOUNT}}" ]'
        msg: "ACCOUNT is required. Usage: task sso:ensure ACCOUNT=<alias>"
    silent: true

  aws-list-accounts:
    desc: "List all configured accounts"
    aliases:
      - list-accounts
    deps:
      - claude:ensure-docker
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - |
        echo "Configured accounts:"
        grep -E "^  [a-z]" aws.yml | grep -v "account_" | sed 's/://g' | sed 's/^  /  - /'
    silent: true

  aws-update:
    desc: "Sync aws.yml with AWS Organizations hierarchy"
    deps:
      - claude:ensure-docker
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - |
        uv run {{.AWS_SCRIPTS_PATH}}/cli/sso_check.py --quiet root || {
          echo "Root account credentials required. Run: task login ACCOUNT=root"
          exit 1
        }
      - uv run {{.AWS_SCRIPTS_PATH}}/cli/org_sync.py {{if .DRY_RUN}}--dry-run{{end}}
    silent: true

  playwright:record:
    desc: Record video of a URL
    vars:
      URL: '{{.URL}}'
      DURATION: '{{.DURATION | default "10"}}'
      OUTPUT: '{{.OUTPUT | default ""}}'
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run --directory .claude/skills/playwright-automation python scripts/video_recorder.py "{{.URL}}" --duration {{.DURATION}} {{if .OUTPUT}}--output "{{.OUTPUT}}"{{end}}
    silent: true

  playwright:screenshot:
    desc: Take screenshot of a URL
    vars:
      URL: '{{.URL}}'
      OUTPUT: '{{.OUTPUT | default ""}}'
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run --directory .claude/skills/playwright-automation python scripts/screenshot.py "{{.URL}}" {{if .OUTPUT}}--output "{{.OUTPUT}}"{{end}}
    silent: true

  playwright:test-twitch:
    desc: uses the playwright to test recording twitch navigation
    deps:
      - claude:ensure-docker
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - |
        uv run --directory .claude/skills/playwright-automation \
          python scripts/test_twitch_navigation.py
    silent: true
