"""
YAML utilities for reading and writing projects.yml.
"""
import os
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml
from loguru import logger


def load_projects_yaml(path: Path) -> dict[str, Any]:
    """Load existing projects.yml or return empty structure."""
    if not path.exists():
        logger.info(f"No existing projects file at {path}")
        return {"projects": {}}

    try:
        with open(path) as f:
            data = yaml.safe_load(f)
        return data if data else {"projects": {}}
    except Exception as e:
        logger.error(f"Error loading {path}: {e}")
        return {"projects": {}}


def save_projects_yaml(path: Path, data: dict[str, Any]) -> bool:
    """Save projects.yml with header comment."""
    try:
        # Ensure parent directory exists
        path.parent.mkdir(parents=True, exist_ok=True)

        # Add header comment
        header = (
            f"# Auto-generated by project-metadata-builder skill\n"
            f"# Last updated: {datetime.now().isoformat()}\n\n"
        )

        with open(path, "w") as f:
            f.write(header)
            yaml.dump(
                data,
                f,
                default_flow_style=False,
                sort_keys=False,
                allow_unicode=True,
                width=120,
            )

        logger.info(f"Saved projects to {path}")
        return True

    except Exception as e:
        logger.error(f"Error saving {path}: {e}")
        return False


def expand_path(path: str) -> Path:
    """Expand ~ and environment variables in path."""
    return Path(os.path.expanduser(os.path.expandvars(path)))
