version: '3'

tasks:

  claude:trivial:
    desc: Create a trivial commit and push
    vars:
      MSG: '{{.MSG | default "(chore) trivial update"}}'
    cmds:
      - pwsh -NoProfile -File .claude/scripts/trivial-commit.ps1 -Message "{{.MSG}}"
    silent: true

  claude:fetch:
    desc: Fetch and reset .claude submodule to origin/main
    cmds:
      - pwsh -NoProfile -File .claude/scripts/fetch-submodule.ps1
    silent: true

  claude:update:
    desc: Commit and sync .claude submodule changes
    vars:
      MSG: '{{.MSG | default "chore: update .claude"}}'
      BRANCH: '{{.BRANCH | default "main"}}'
    cmds:
      - pwsh -NoProfile -File .claude/scripts/update-submodule.ps1 -Message "{{.MSG}}" -Branch "{{.BRANCH}}"
    silent: true

  claude:claude:
    aliases:
      - claude
    cmds:
      - task --dir ./.claude claude
    silent: true

  claude:shell:
    cmds:
      - task --dir ./.claude shell
    silent: true

  claude:clean:
    cmds:
      - task --dir ./.claude clean
    silent: true

  claude:purge:
    cmds:
      - task --dir ./.claude purge
    silent: true

  claude:nuke:
    cmds:
      - task --dir ./.claude purge
    silent: true

  claude:build:
    cmds:
      - task --dir ./.claude build
    silent: true

  claude:config:
    cmds:
      - task --dir ./.claude config
    silent: true
