version: '3'

tasks:

  claude:trivial:
    desc: creates a commit with a '{{.MSG}}' message and pushes it
    vars:
      MSG: '{{.MSG | default "(chore) trivial update"}}'
    preconditions:
      - sh: '[ -n "$(git status --porcelain)" ]'
        msg: "No changes to commit"
    cmds:
      - git status
      - git add --all
      - git commit -m '{{.MSG}}'
      - git push
      - git status
    silent: true

  claude:fetch:
    cmds:
      - git config --global fetch.recurseSubmodules true
      - git config --global submodule.recurse true
      - git submodule sync --recursive
      - git -C .claude fetch origin && git -C .claude reset --hard origin/main
      - git -C .claude clean -fd
    silent: true

  claude:update:
    desc: Commit and sync .claude submodule changes
    vars:
      MSG: '{{.MSG | default "chore: update .claude"}}'
      BRANCH: '{{.BRANCH | default "main"}}'
      GIT_DIR:
        sh: '[ -d .claude ] && echo ".claude" || echo "."'
    preconditions:
      - sh: |
          git -C {{.GIT_DIR}} fetch --all -q
          git -C {{.GIT_DIR}} status | grep -q "Your branch is behind" || [ -n "$(git -C {{.GIT_DIR}} status --porcelain)" ]
        msg: "Submodule is already up to date and has no local changes"
    cmds:
      - git -C {{.GIT_DIR}} add --all
      - git -C {{.GIT_DIR}} diff --cached --quiet || git -C {{.GIT_DIR}} commit -m "{{.MSG}}"
      - git -C {{.GIT_DIR}} push
      - git -C {{.GIT_DIR}} pull origin {{.BRANCH}}
    silent: true

  claude:claude:
    aliases:
      - claude
    cmds:
      - task --dir ./.claude claude
    silent: true

  claude:shell:
    cmds:
      - task --dir ./.claude shell
    silent: true

  claude:clean:
    cmds:
      - task --dir ./.claude clean
    silent: true

  claude:purge:
    cmds:
      - task --dir ./.claude purge
    silent: true

  claude:nuke:
    cmds:
      - task --dir ./.claude purge
    silent: true

  claude:build:
    cmds:
      - task --dir ./.claude build
    silent: true

  claude:config:
    cmds:
      - task --dir ./.claude config
    silent: true
